### POST REQUEST TO CREATE USER
POST http://localhost:3001/api/user
Content-Type: application/json

{
  "firstName": "l2Mohamed13-37",
  "lastName": "l1Darify13-37",
  "providerId": 1337,
  "provider": "google",
  "username": "l52Sdarify1337",
  "email": "Msdarify4513-3f7@gmail.com",
  "picture": "http://google.com/picture.jpg"
}

### GET  ALL USERS IN DATABASE 
GET http://localhost:3001/api/user/all

### GET USER BY ID
GET http://localhost:3001/api/user/id/322f7886-91dc-4052-bcb8-763f71627fc8

### GET USER BY ID
GET http://localhost:3001/api/user/email/darify1337@gmail.com

### GET USER BY TOKEN
GET http://localhost:3001/api/user/accessToken/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiMzIyZjc4ODYtOTFkYy00MDUyLWJjYjgtNzYzZjcxNjI3ZmM4IiwiY3JlYXRlZEF0IjoiMjAyNC0wOS0xNFQxMDoxODozNS42NjFaIiwidXBkYXRlZEF0IjoiMjAyNC0wOS0xNFQxMDoxODozNS42NjFaIiwiZmlyc3ROYW1lIjoiRGFyaWZ5IiwibGFzdE5hbWUiOiJNb2hhbWVkIiwicGljdHVyZSI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hL0FDZzhvY0o1WjdtOGU4THFqUTFEcnBqTmZsX2pkZDdSWHFjdnRXU1ZGZWFIMXRJOFlXczlsLWs2PXM5Ni1jIiwicHJvdmlkZXIiOiJnb29nbGUiLCJlbWFpbCI6ImRhcmlmeTEzMzdAZ21haWwuY29tIiwidXNlcm5hbWUiOiJNb2hhbWVkIERhcmlmeSJ9LCJwcm92aWRlciI6Imdvb2dsZSIsImlhdCI6MTcyNjM4NDk3OSwiZXhwIjoxNzI2NDcxMzc5fQ.Z6pINwmUmoHXL2KafeBqph9WOmtC8LuRzua8zzICbKM
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiMzIyZjc4ODYtOTFkYy00MDUyLWJjYjgtNzYzZjcxNjI3ZmM4IiwiY3JlYXRlZEF0IjoiMjAyNC0wOS0xNFQxMDoxODozNS42NjFaIiwidXBkYXRlZEF0IjoiMjAyNC0wOS0xNFQxMDoxODozNS42NjFaIiwiZmlyc3ROYW1lIjoiRGFyaWZ5IiwibGFzdE5hbWUiOiJNb2hhbWVkIiwicGljdHVyZSI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hL0FDZzhvY0o1WjdtOGU4THFqUTFEcnBqTmZsX2pkZDdSWHFjdnRXU1ZGZWFIMXRJOFlXczlsLWs2PXM5Ni1jIiwicHJvdmlkZXIiOiJnb29nbGUiLCJlbWFpbCI6ImRhcmlmeTEzMzdAZ21haWwuY29tIiwidXNlcm5hbWUiOiJNb2hhbWVkIERhcmlmeSJ9LCJwcm92aWRlciI6Imdvb2dsZSIsImlhdCI6MTcyNjM4NDk3OSwiZXhwIjoxNzI2NDcxMzc5fQ.Z6pINwmUmoHXL2KafeBqph9WOmtC8LuRzua8zzICbKM