### POST REQUEST TO CREATE USER WITH GOOGLE AUTHENTICATION
POST http://localhost:3001/api/user
Content-Type: application/json

 {
    "id": "7ed29149-6293-4dcc-b937-2f694c52af13",
    "createdAt": "2024-09-28T10:31:07.305Z",
    "updatedAt": "2024-09-28T10:31:07.305Z",
    "firstName": "l2Mohamed13-37",
    "lastName": "l1Darify13-37",
    "picture": "http://google.com/picture.jpg",
    "provider": "google",
    "email": "Msdarify4513-3f7@gmail.com",
    "username": "l52Sdarify1337"
  }



### POST REQUEST TO CREATE USER WITH SIGN UP
POST http://localhost:3001/api/signup/signup
Content-Type: application/json

{
  "firstName": "khalil",
  "lastName" :"id_13",
  "provider": "signup",
  "picture" : "www.google.com",
  "username": "khalild_",
  "email": "khallidl1_1337@gmail.com",
  "password": "Darify1337@",
  "confirmPassword": "Darify1337@"
}


### POST REQUEST TO SIGN IN OF USER
POST  http://localhost:3001/api/user/signin
Content-Type: application/json

{
  "email": "khalid@gmail.com",
  "password": "Darify1337@"
}

### GET  ALL USERS IN DATABASE 
GET http://localhost:3001/api/user/all

### GET USER BY ID
GET http://localhost:3001/api/user/id/322f7886-91dc-4052-bcb8-763f71627fc8

### GET USER BY ID
GET http://localhost:3001/api/user/email/darify1337@gmail.com

### GET USER BY TOKEN
GET http://localhost:3001/api/user/accessToken/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MjgxMzYxMDUsImV4cCI6MTcyODc0MDkwNX0.W1B3BU5XGexoq9JfJ-yBsBTPQu7e4exUgOHlxxVQMx8
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MjgxMzYxMDUsImV4cCI6MTcyODc0MDkwNX0.W1B3BU5XGexoq9JfJ-yBsBTPQu7e4exUgOHlxxVQMx8


### GET ALL USERS LOGIN WIHT SING UP IN DATABASE
GET http://localhost:3001/api/user/all


### GET sorted users
GET http://localhost:3001/api/user/sorted
