import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/NavBar";
import './style.css'
// import { UserProvider } from "@/context/userContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' >
      <body className={`${inter.className}  `}>
          <main className='h-screen bg-black flex 
            flex-col  items-center backgroundbody justify-center'>
            {/* <Navbar /> */}

            {children}
          </main>
          
      </body>
    </html>
  );
}
